apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  namespace: _your_namespace_
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - _your_domain_
    secretName: quickstart-example-tls
  rules:
  - host: _your_domain_
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard
          servicePort: 80
